# libqemu Makefile.uk
#
# Authors: Maria Sfiraiala <maria.sfiraiala@gmail.com>
#
# Copyright (c) 2021, University Politehnica of Bucharest. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libqemu,$(CONFIG_LIBQEMU)))

################################################################################
# Sources
################################################################################
LIBQEMU_VERSION=8.1.2
LIBQEMU_URL=https://download.qemu.org/qemu-$(LIBQEMU_VERSION).tar.xz
LIBQEMU_DIR=qemu-$(LIBQEMU_VERSION)/
LIBQEMU_PATCHDIR=$(LIBQEMU_BASE)/patches

$(eval $(call fetch,libqemu,$(LIBQEMU_URL)))
$(eval $(call patch,libqemu,$(LIBQEMU_PATCHDIR),$(LIBQEMU_DIR)))

################################################################################
# Helpers
################################################################################
LIBQEMU=$(LIBQEMU_ORIGIN)/$(LIBQEMU_DIR)

# Additional macros for qemu sub-libraries
include $(LIBQEMU_BASE)/Makefile.rules
$(LIBQEMU_BUILD)/.prepared: $(LIBQEMU_BUILD)/.patched
	touch $@
UK_PREPARE += $(LIBQEMU_BUILD)/.prepared

################################################################################
# Library includes
################################################################################
CINCLUDES-$(CONFIG_LIBQEMU)  += -I$(LIBQEMU_BASE)/include
CXXINCLUDES-$(CONFIG_LIBQEMU) += -I$(LIBQEMU_BASE)/include

CINCLUDES-$(CONFIG_LIBQEMU)   += -I$(LIBQEMU)
CXXINCLUDES-$(CONFIG_LIBQEMU) += -I$(LIBQEMU)

################################################################################
# Global flags
################################################################################
LIBQEMU_SUPPRESS_FLAGS += -Wno-unused-parameter   \
	      -Wno-unused-variable            \
		  -Wno-unused-value               \
		  -Wno-unused-function            \
		  -Wno-missing-field-initializers \
		  -Wno-implicit-fallthrough \
          -Wno-implicit-function-declaration \
          -Wno-int-conversion

LIBQEMU_CFLAGS-y   += $(LIBQEMU_SUPPRESS_FLAGS) \
		      -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast
LIBQEMU_CFLAGS-y   += -DCONFIG_TARGET=\"x86_64-softmmu-config-target.h\" -DCONFIG_DEVICES=\"x86_64-softmmu-config-devices.h\"
LIBQEMU_CFLAGS-y   += -DNEED_CPU_H
LIBQEMU_CXXFLAGS-y += $(LIBQEMU_SUPPRESS_FLAGS)

CFLAGS-$(CONFIG_LIBQEMU) += $(LIBQEMU_HDRS_FLAGS-y)
CXXFLAGS-$(CONFIG_LIBQEMU) += $(LIBQEMU_HDRS_FLAGS-y)

################################################################################
# QEMU code -- one external Makefile per sub-lib
################################################################################
include $(LIBQEMU_BASE)/Makefile.uk.qemu.authz
include $(LIBQEMU_BASE)/Makefile.uk.qemu.block
include $(LIBQEMU_BASE)/Makefile.uk.qemu.blockdev
include $(LIBQEMU_BASE)/Makefile.uk.qemu.chardev
include $(LIBQEMU_BASE)/Makefile.uk.qemu.common
include $(LIBQEMU_BASE)/Makefile.uk.qemu.crypto
include $(LIBQEMU_BASE)/Makefile.uk.qemu.event-loop-base
include $(LIBQEMU_BASE)/Makefile.uk.qemu.fdt
include $(LIBQEMU_BASE)/Makefile.uk.qemu.gdb_softmmu
include $(LIBQEMU_BASE)/Makefile.uk.qemu.gdb_user
include $(LIBQEMU_BASE)/Makefile.uk.qemu.hwcore
include $(LIBQEMU_BASE)/Makefile.uk.qemu.io
include $(LIBQEMU_BASE)/Makefile.uk.qemu.migration
include $(LIBQEMU_BASE)/Makefile.uk.qemu.qemuutil
include $(LIBQEMU_BASE)/Makefile.uk.qemu.qemu-x86_64-softmmu
include $(LIBQEMU_BASE)/Makefile.uk.qemu.qmp
include $(LIBQEMU_BASE)/Makefile.uk.qemu.qom
include $(LIBQEMU_BASE)/Makefile.uk.qemu.qos

################################################################################
# QEMU prepare
################################################################################
# Run ./configure
$(LIBQEMU_BUILD)/.configured: $(LIBQEMU_BUILD)/.prepared
	$(call verbose_cmd,CONFIG,libqemu: $(notdir $@), \
	cd $(LIBQEMU) && ./configure \
        --cxx=/non-existent \
        --disable-attr \
        --disable-auth-pam \
        --disable-bochs \
        --disable-brlapi \
        --disable-bzip2 \
        --disable-cap-ng \
        --disable-cloop \
        --disable-cocoa \
        --disable-coroutine-pool \
        --disable-crypto-afalg \
        --disable-curl \
        --disable-curses \
        --disable-dmg \
        --disable-docs \
        --disable-gcrypt \
        --disable-glusterfs \
        --disable-gnutls \
        --disable-gtk \
        --disable-guest-agent \
        --disable-hax \
        --disable-kvm \
        --disable-libiscsi \
        --disable-libnfs \
        --disable-libssh \
        --disable-linux-aio \
        --disable-live-block-migration \
        --disable-lzo \
        --disable-netmap \
        --disable-nettle \
        --disable-numa \
        --disable-opengl \
        --disable-parallels \
        --disable-qcow1 \
        --disable-qed \
        --disable-qom-cast-debug \
        --disable-rbd \
        --disable-rdma \
        --disable-replication \
        --disable-sdl \
        --disable-slirp \
        --disable-smartcard \
        --disable-snappy \
        --disable-spice \
        --disable-spice \
        --disable-tcg \
        --disable-tools \
        --disable-tpm \
        --disable-usb-redir \
        --disable-vde \
        --disable-vdi \
        --disable-vhost-crypto \
        --disable-vhost-net \
        --disable-vhost-user \
        --disable-virglrenderer \
        --disable-virglrenderer \
        --disable-virtfs \
        --disable-vnc \
        --disable-vte \
        --disable-vvfat \
        --disable-werror \
        --enable-pie \
        --enable-rng-none \
        --enable-trace-backends=log \
        --enable-xen \
        --enable-xen-pci-passthrough \
        --prefix=/usr \
        --target-list=x86_64-softmmu \
        --without-default-features \
    && $(LIBQEMU_BASE)/helpers/custom_commands.sh $(LIBQEMU) && touch $@)

UK_PREPARE += $(LIBQEMU_BUILD)/.configured
