#pragma GCC poison CONFIG_ACPI
#pragma GCC poison CONFIG_ACPI_HW_REDUCED
#pragma GCC poison CONFIG_ACPI_ICH9
#pragma GCC poison CONFIG_ACPI_PCI
#pragma GCC poison CONFIG_ACPI_PCI_BRIDGE
#pragma GCC poison CONFIG_ACPI_PCIHP
#pragma GCC poison CONFIG_ACPI_PIIX4
#pragma GCC poison CONFIG_ACPI_SMBUS
#pragma GCC poison CONFIG_ACPI_VIOT
#pragma GCC poison CONFIG_ACPI_VMGENID
#pragma GCC poison CONFIG_ACPI_X86
#pragma GCC poison CONFIG_AHCI
#pragma GCC poison CONFIG_AHCI_ICH9
#pragma GCC poison CONFIG_AMD_IOMMU
#pragma GCC poison CONFIG_APIC
#pragma GCC poison CONFIG_APM
#pragma GCC poison CONFIG_BITBANG_I2C
#pragma GCC poison CONFIG_CAN_BUS
#pragma GCC poison CONFIG_CAN_CTUCANFD
#pragma GCC poison CONFIG_CAN_CTUCANFD_PCI
#pragma GCC poison CONFIG_CAN_PCI
#pragma GCC poison CONFIG_CAN_SJA1000
#pragma GCC poison CONFIG_E1000E_PCI_EXPRESS
#pragma GCC poison CONFIG_E1000_PCI
#pragma GCC poison CONFIG_FW_CFG_DMA
#pragma GCC poison CONFIG_GENERIC_LOADER
#pragma GCC poison CONFIG_I2C
#pragma GCC poison CONFIG_I386_DIS
#pragma GCC poison CONFIG_I8254
#pragma GCC poison CONFIG_I8257
#pragma GCC poison CONFIG_I8259
#pragma GCC poison CONFIG_I82801B11
#pragma GCC poison CONFIG_IDE_CORE
#pragma GCC poison CONFIG_IDE_ISA
#pragma GCC poison CONFIG_IDE_PCI
#pragma GCC poison CONFIG_IDE_PIIX
#pragma GCC poison CONFIG_IDE_QDEV
#pragma GCC poison CONFIG_IGB_PCI_EXPRESS
#pragma GCC poison CONFIG_IMX_USBPHY
#pragma GCC poison CONFIG_IOAPIC
#pragma GCC poison CONFIG_IOH3420
#pragma GCC poison CONFIG_IPACK
#pragma GCC poison CONFIG_ISA_BUS
#pragma GCC poison CONFIG_ISA_DEBUG
#pragma GCC poison CONFIG_ISA_IPMI_BT
#pragma GCC poison CONFIG_ISA_IPMI_KCS
#pragma GCC poison CONFIG_ISAPC
#pragma GCC poison CONFIG_ISA_TESTDEV
#pragma GCC poison CONFIG_IVSHMEM_DEVICE
#pragma GCC poison CONFIG_LPC_ICH9
#pragma GCC poison CONFIG_LSI_SCSI_PCI
#pragma GCC poison CONFIG_MC146818RTC
#pragma GCC poison CONFIG_MEGASAS_SCSI_PCI
#pragma GCC poison CONFIG_MEM_DEVICE
#pragma GCC poison CONFIG_MICROVM
#pragma GCC poison CONFIG_MPTSAS_SCSI_PCI
#pragma GCC poison CONFIG_MSI_NONBROKEN
#pragma GCC poison CONFIG_NE2000_COMMON
#pragma GCC poison CONFIG_NE2000_ISA
#pragma GCC poison CONFIG_NE2000_PCI
#pragma GCC poison CONFIG_NMC93XX_EEPROM
#pragma GCC poison CONFIG_PARALLEL
#pragma GCC poison CONFIG_PC_ACPI
#pragma GCC poison CONFIG_PCI
#pragma GCC poison CONFIG_PCI_DEVICES
#pragma GCC poison CONFIG_PCIE_PCI_BRIDGE
#pragma GCC poison CONFIG_PCIE_PORT
#pragma GCC poison CONFIG_PCI_EXPRESS
#pragma GCC poison CONFIG_PCI_EXPRESS_GENERIC_BRIDGE
#pragma GCC poison CONFIG_PCI_IPMI_BT
#pragma GCC poison CONFIG_PCI_IPMI_KCS
#pragma GCC poison CONFIG_PCI_TESTDEV
#pragma GCC poison CONFIG_PCKBD
#pragma GCC poison CONFIG_PCNET_COMMON
#pragma GCC poison CONFIG_PCNET_PCI
#pragma GCC poison CONFIG_PC_PCI
#pragma GCC poison CONFIG_PCSPK
#pragma GCC poison CONFIG_PFLASH_CFI01
#pragma GCC poison CONFIG_PIIX3
#pragma GCC poison CONFIG_PS2
#pragma GCC poison CONFIG_PVPANIC_COMMON
#pragma GCC poison CONFIG_PVPANIC_ISA
#pragma GCC poison CONFIG_PVPANIC_PCI
#pragma GCC poison CONFIG_ROCKER
#pragma GCC poison CONFIG_RTL8139_PCI
#pragma GCC poison CONFIG_SB16
#pragma GCC poison CONFIG_SCSI
#pragma GCC poison CONFIG_SD
#pragma GCC poison CONFIG_SDHCI
#pragma GCC poison CONFIG_SDHCI_PCI
#pragma GCC poison CONFIG_SERIAL
#pragma GCC poison CONFIG_SERIAL_ISA
#pragma GCC poison CONFIG_SERIAL_PCI
#pragma GCC poison CONFIG_SERIAL_PCI_MULTI
#pragma GCC poison CONFIG_SMBIOS
#pragma GCC poison CONFIG_SMBUS
#pragma GCC poison CONFIG_SYSTEM_ONLY
#pragma GCC poison CONFIG_USB
#pragma GCC poison CONFIG_USB_AUDIO
#pragma GCC poison CONFIG_USB_CANOKEY
#pragma GCC poison CONFIG_USB_EHCI
#pragma GCC poison CONFIG_USB_EHCI_PCI
#pragma GCC poison CONFIG_USB_NETWORK
#pragma GCC poison CONFIG_USB_OHCI
#pragma GCC poison CONFIG_USB_OHCI_PCI
#pragma GCC poison CONFIG_USB_SERIAL
#pragma GCC poison CONFIG_USB_SMARTCARD
#pragma GCC poison CONFIG_USB_STORAGE_BOT
#pragma GCC poison CONFIG_USB_STORAGE_CLASSIC
#pragma GCC poison CONFIG_USB_STORAGE_CORE
#pragma GCC poison CONFIG_USB_STORAGE_MTP
#pragma GCC poison CONFIG_USB_STORAGE_UAS
#pragma GCC poison CONFIG_USB_TABLET_WACOM
#pragma GCC poison CONFIG_USB_U2F
#pragma GCC poison CONFIG_USB_UHCI
#pragma GCC poison CONFIG_USB_XHCI
#pragma GCC poison CONFIG_USB_XHCI_NEC
#pragma GCC poison CONFIG_USB_XHCI_PCI
#pragma GCC poison CONFIG_USB_XHCI_SYSBUS
#pragma GCC poison CONFIG_VIRTIO
#pragma GCC poison CONFIG_VIRTIO_BALLOON
#pragma GCC poison CONFIG_VIRTIO_BLK
#pragma GCC poison CONFIG_VIRTIO_CRYPTO
#pragma GCC poison CONFIG_VIRTIO_INPUT
#pragma GCC poison CONFIG_VIRTIO_INPUT_HOST
#pragma GCC poison CONFIG_VIRTIO_IOMMU
#pragma GCC poison CONFIG_VIRTIO_MD
#pragma GCC poison CONFIG_VIRTIO_MEM
#pragma GCC poison CONFIG_VIRTIO_MEM_SUPPORTED
#pragma GCC poison CONFIG_VIRTIO_MMIO
#pragma GCC poison CONFIG_VIRTIO_NET
#pragma GCC poison CONFIG_VIRTIO_PCI
#pragma GCC poison CONFIG_VIRTIO_PMEM
#pragma GCC poison CONFIG_VIRTIO_PMEM_SUPPORTED
#pragma GCC poison CONFIG_VIRTIO_RNG
#pragma GCC poison CONFIG_VIRTIO_SCSI
#pragma GCC poison CONFIG_VIRTIO_SERIAL
#pragma GCC poison CONFIG_VMMOUSE
#pragma GCC poison CONFIG_VMPORT
#pragma GCC poison CONFIG_VMW_PVSCSI_SCSI_PCI
#pragma GCC poison CONFIG_VMXNET3_PCI
#pragma GCC poison CONFIG_VTD
#pragma GCC poison CONFIG_X86_IOMMU
#pragma GCC poison CONFIG_XEN
#pragma GCC poison CONFIG_XEN_BUS
#pragma GCC poison CONFIG_XIO3130
#pragma GCC poison QEMU_ARCH
#pragma GCC poison TARGET_BIG_ENDIAN
#pragma GCC poison TARGET_I386
#pragma GCC poison TARGET_NAME
#pragma GCC poison TARGET_NEED_FDT
#pragma GCC poison TARGET_SUPPORTS_MTTCG
#pragma GCC poison TARGET_X86_64
